---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apacheds
  name: apacheds
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apacheds
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apacheds
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom
        - name: fortriggerupdates
          value: changeme
        - name: APACHEDS_ROOT_PASSWORD
          value: start123
        - name: APACHEDS_TLS_KS_PWD
          value: start123
        - name: DN
          value: dc=domain,dc=com
        - name: OBJECT_CLASS
          value: domain
        - name: LDIF_FILE
          value: /etc/apacheds/data.ldif
        image: tremolosecurity/apacheds:latest
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 10389
          failureThreshold: 10
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: apacheds
        ports:
        - containerPort: 10389
          name: ldap
          protocol: TCP
        - containerPort: 10636
          name: ldaps
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 10389
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/apacheds
          name: secret-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: apacheds-secret
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-03-28T00:28:04Z"
  labels:
    app: apacheds
  name: apacheds
spec:
  ports:
  - name: apacheds-ldap
    port: 389
    protocol: TCP
    targetPort: 10389
  - name: apacheds-ldaps
    port: 636
    protocol: TCP
    targetPort: 10636
  selector:
    app: apacheds
  type: NodePort
status:
  loadBalancer: {}